In [1]:
import pandas as pd

df = pd.read_csv('customer_shopping_behavior_realistic.csv')
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Dress,Accessories,79.24,Kentucky,L,Gray,Winter,3.1,No,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Shirt,Clothing,112.00,Maine,L,Maroon,Summer,3.1,Yes,Free Shipping,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Pants,Footwear,73.00,Massachusetts,S,Maroon,Spring,3.1,No,Standard,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Dress,Accessories,112.50,Rhode Island,M,Maroon,Summer,3.5,Yes,Store Pickup,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Handbag,Clothing,68.60,Oregon,M,Turquoise,Spring,2.7,No,Standard,Yes,Yes,31,PayPal,Annually

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 18 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   customer_id             600000 non-null  int64
 1   age                     600000 non-null  int64
 2   gender                  600000 non-null  object
 3   item_purchased          600000 non-null  object
 4   category                600000 non-null  object
 5   purchase_amount_usd     600000 non-null  float64
 6   location                600000 non-null  object
 7   size                    600000 non-null  object
 8   color                   600000 non-null  object
 9   season                  600000 non-null  object
 10  review_rating           594324 non-null  float64
 11  subscription_status     600000 non-null  object
 12  shipping_type           600000 non-null  object
 13  discount_applied        600000 non-null  object
 14  promo_code_used         600000 non-null  object
 15  previous_purchases      600000 non-null  int64
 16  payment_method          600000 non-null  object
 17  frequency_of_purchases  600000 non-null  object
dtypes: float64(2), int64(3), object(13)
memory usage: 82.4+ MB

In [3]:
# Summary statistics using .describe()
df.describe(include='all')#for both numerical and categorical columne

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
count,600000.000000,600000.000000,600000,600000,600000,600000.000000,600000,600000,600000,600000,594324.000000,600000,600000,600000,600000,600000.000000,600000,600000
unique,NaN,NaN,2,10,4,NaN,50,4,25,4,NaN,2,5,2,2,NaN,6,7
top,NaN,NaN,Male,Shirt,Clothing,NaN,California,M,Olive,Winter,NaN,No,Standard,Yes,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,408223,119767,299872,NaN,14582,270666,26962,220024,NaN,419758,249835,359221,342557,NaN,104235,90181
mean,1951.671280,44.159187,NaN,NaN,NaN,100.455331,NaN,NaN,NaN,NaN,3.749577,NaN,NaN,NaN,NaN,26.349297,NaN,NaN
std,1125.405654,15.628906,NaN,NaN,NaN,59.938123,NaN,NaN,NaN,NaN,0.717434,NaN,NaN,NaN,NaN,14.871147,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,10.020000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
25%,976.000000,31.000000,NaN,NaN,NaN,54.910000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,14.000000,NaN,NaN
50%,1953.000000,44.000000,NaN,NaN,NaN,86.840000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,26.000000,NaN,NaN
75%,2926.000000,57.000000,NaN,NaN,NaN,133.230000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,39.000000,NaN,NaN
max,3900.000000,77.000000,NaN,NaN,NaN,466.520000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,57.000000,NaN,NaN

In [4]:
# Checking if missing data or null values are present in the dataset

df.isnull().sum()

customer_id                  0
age                          0
gender                       0
item_purchased               0
category                     0
purchase_amount_usd          0
location                     0
size                         0
color                        0
season                       0
review_rating             5676
subscription_status          0
shipping_type                0
discount_applied             0
promo_code_used              0
previous_purchases           0
payment_method               0
frequency_of_purchases       0
dtype: int64

In [5]:
df["review_rating"] = df.groupby("category")["review_rating"].transform(
    lambda x: x.fillna(x.median())
)

In [6]:
df.isnull().sum()

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchase_amount_usd       0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
promo_code_used           0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
dtype: int64

In [7]:
# Renaming columns according to snake casing for better readability and documentation

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [8]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [9]:
# create a new column age_group
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [10]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [11]:
# create new column purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [12]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [13]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [14]:
(df['discount_applied'] == df['promo_code_used']).all()

np.False_

In [15]:
# Dropping promo code used column

df = df.drop('promo_code_used', axis=1)

In [16]:
# Rename columns
df.rename(columns={
    'purchase_amount_usd': 'purchase_amount'
}, inplace=True)

In [17]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [19]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.14.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"      # default user
password = "postgres" # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "customer_behavior_33"    # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

In [21]:
import pandas as pd

# Load CSV file
df = pd.read_csv("customer_shopping_behavior_60k.csv")

# Rename columns
df.rename(columns={
    'purchase_amount_usd': 'purchase_amount'
}, inplace=True)

# Check updated columns
print(df.columns)

# Save updated CSV file
df.to_csv("customer_analysis_updated.csv", index=False)

print("Column renamed successfully!")

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')
Column renamed successfully!